"""
toolkit/governance.py
Tribal Data Sovereignty Toolkit

Configurable governance framework module.
Generates governance statements, data sharing agreements,
and compliance checklists from a NationConfig.

CLI usage
python toolkit/governance.py --config config/nation.yaml --validate
python toolkit/governance.py --config config/nation.yaml --statement
python toolkit/governance.py --config config/nation.yaml --checklist
"""

from __future__ import annotations

import sys
from pathlib import Path


def data_sovereignty_statement(ctx) -> str:
    """
    Generate a full data sovereignty statement for a Nation.
    Suitable for inclusion in README files, publications, and
    data package documentation.
    """
    cfg = ctx.config
    fw_lines = []
    fw_labels = {
        "ocap":           ("OCAP®",
                           "Ownership, Control, Access, and Possession",
                           cfg.framework_refs.get("ocap","")),
        "care":           ("CARE Principles",
                           "Collective Benefit, Authority to Control, Responsibility, Ethics",
                           cfg.framework_refs.get("care","")),
        "fair":           ("FAIR Principles",
                           "Findable, Accessible, Interoperable, Reusable",
                           cfg.framework_refs.get("fair","")),
        "ieee_2890":      ("IEEE 2890-2025",
                           "Recommended Practice for Provenance of Indigenous Peoples' Data",
                           cfg.framework_refs.get("ieee_2890","")),
        "local_contexts": ("Local Contexts",
                           "Traditional Knowledge Labels and Notices",
                           cfg.framework_refs.get("local_contexts","")),
    }
    for fw, enabled in cfg.frameworks_enabled.items():
        if enabled and fw in fw_labels:
            label, desc, ref = fw_labels[fw]
            fw_lines.append(f"  {label}: {desc}\n  Reference: {ref}")

    legal_str = ""
    if cfg.legal_citations:
        legal_str = "\n  ".join(cfg.legal_citations)

    statement = f"""DATA SOVEREIGNTY STATEMENT
{'='*65}

NATION AND TERRITORY
  Nation    : {cfg.name}"""

    if cfg.collective:
        statement += f"\n  Collective: {cfg.collective}"

    statement += f"""
  Territory : {cfg.territory}

TERRITORIAL PROVENANCE
  Treaty    : {cfg.treaty_name}
  Territory : {cfg.treaty_territory}

  {cfg.treaty_status}
"""

    if legal_str:
        statement += f"\n  Legal citation: {legal_str}\n"

    if cfg.subsurface_note:
        statement += f"\n  Subsurface note: {cfg.subsurface_note}\n"

    statement += f"""
GOVERNANCE FRAMEWORKS
  This work is governed by the following Indigenous data sovereignty
  frameworks:

"""
    for line in fw_lines:
        statement += f"  {line}\n\n"

    statement += f"""DATA STEWARDSHIP
  Primary steward : {cfg.department}
"""
    if cfg.contact_url:
        statement += f"  Contact         : {cfg.contact_url}\n"

    statement += f"""
  {cfg.contact_note}

ACKNOWLEDGMENT
  {cfg.acknowledgment}

CITATION
  {cfg.citation_format}
{'─'*65}
Generated by the Tribal Data Sovereignty Toolkit
Daear Consulting, LLC
"""
    return statement


def compliance_checklist(ctx) -> str:
    """
    Generate a governance compliance checklist for a project.
    Returns a markdown-formatted checklist.
    """
    cfg = ctx.config

    checklist = f"""# Data Governance Compliance Checklist
**Nation:** {cfg.name}  
**Territory:** {cfg.territory}  
**Frameworks:** {', '.join(f.upper() for f, v in cfg.frameworks_enabled.items() if v)}

---

## Before Data Collection

- [ ] Tribal governance body has approved this data collection
- [ ] Data governance agreement or MOU is signed and on file
- [ ] Community benefit plan is documented
- [ ] Data classification scheme is agreed upon with Tribal steward
- [ ] Tribal department ({cfg.department}) has been notified
- [ ] Sensitive location and cultural knowledge protocols are in place

## During Data Collection

- [ ] Field data is stored locally (and gitignored) 
- [ ] Collectors understand OCAP® principles and data classification
- [ ] Field observations use standardized templates (from `templates/`)
- [ ] GPS coordinates are reviewed for cultural sensitivity before logging
- [ ] Regular check-ins with Tribal steward are occurring

## Data Processing

- [ ] Processing steps are documented in provenance records
- [ ] Derived datasets inherit governance obligations of source data
- [ ] Data classification is attached to every output file
- [ ] Sensitive fields are not included in public-facing outputs
- [ ] Version control is clean (no Tribal data committed to git)

## Before Publication or Sharing

- [ ] Findings have been returned to the Tribal community first
- [ ] {cfg.department} has reviewed and approved for external sharing
- [ ] All maps reviewed for sensitive location disclosure
- [ ] Data sovereignty statement is included in every output
- [ ] IEEE 2890-2025 provenance records are complete
- [ ] DOI or persistent identifier is assigned (if making public)
- [ ] License reflects CARE and OCAP® constraints (not just open license)

## After Publication

- [ ] Tribal Nation holds a copy of all data and publications
- [ ] Findings are communicated to community in accessible format
- [ ] Data governance agreement covers ongoing responsibilities
- [ ] Contact information for questions is documented

---

## Framework References

"""
    fw_labels = {
        "ocap":           "OCAP®",
        "care":           "CARE Principles",
        "fair":           "FAIR Principles",
        "ieee_2890":      "IEEE 2890-2025",
        "local_contexts": "Local Contexts",
    }
    for fw, enabled in cfg.frameworks_enabled.items():
        if enabled:
            label = fw_labels.get(fw, fw.upper())
            ref   = cfg.framework_refs.get(fw, "")
            checklist += f"- **{label}:** {ref}\n"

    checklist += f"""
---
*Generated by the Tribal Data Sovereignty Toolkit*  
*Daear Consulting, LLC*
"""
    return checklist


def data_sharing_template(ctx, project_name: str = "[Project Name]") -> str:
    """
    Generate a data sharing agreement template for a specific project.
    This is a starting-point template, legal review by Tribal legal
    counsel must occur before use.
    """
    cfg = ctx.config

    return f"""DATA SHARING AND GOVERNANCE AGREEMENT
TEMPLATE: Requires Tribal legal review before use

PROJECT: {project_name}
NATION:  {cfg.name}
DATE:    [Date]

PARTIES
  The {cfg.name} ({cfg.territory}), hereinafter "the Nation"
  [Researcher/Institution Name], hereinafter "the Researcher"

TERRITORIAL ACKNOWLEDGMENT
  The data described in this agreement pertains to the lands, waters,
  and communities of the {cfg.name} people of {cfg.territory}.
  This agreement recognizes the Nation's sovereign authority over
  data about their territory and community members.

  Treaty basis: {cfg.treaty_name} ({cfg.treaty_territory})

DATA OWNERSHIP (OCAP® Ownership)
  All data collected on or about {cfg.territory} under this agreement
  is owned by the {cfg.name} Nation. The Researcher does not acquire
  ownership rights to any data through this agreement.

DATA CONTROL (OCAP® Control)
  The Nation retains the right to:
  a) Review all data products before external publication or sharing
  b) Decline to authorize publication of any specific finding
  c) Suspend or terminate data collection at any time
  d) Require modification of analysis methods or framing

DATA ACCESS (OCAP® Access)
  The Researcher agrees to:
  a) Return all data and findings to the Nation in accessible formats
  b) Provide community-readable summaries of all technical findings
  c) Grant Nation staff access to all data systems used in this project

DATA POSSESSION (OCAP® Possession)
  The Researcher agrees to:
  a) Provide the Nation with a complete copy of all collected data
  b) Not be the sole custodian of data about the Nation's territory
  c) Ensure the Nation retains access after this agreement ends

GOVERNANCE FRAMEWORKS
  This agreement is governed by:
  - OCAP® Principles (https://fnigc.ca/ocap-training/)
  - CARE Principles (https://www.gida-global.org/care)
  - FAIR Principles (https://www.go-fair.org/fair-principles/)
  - IEEE 2890-2025 (https://standards.ieee.org/ieee/2890/10318/)

DATA CLASSIFICATION
  Data collected under this agreement shall be classified as:
  [ ] PUBLIC: may be shared freely
  [ ] COMMUNITY: Tribal members and authorized partners only
  [ ] RESTRICTED: Tribal governance only
  [ ] GITIGNORED: Never uploaded to version control or cloud

STEWARDSHIP
  Primary Tribal steward: {cfg.department}
  {"Contact: " + cfg.contact_url if cfg.contact_url else ""}

SIGNATURES
  For the {cfg.name} Nation:
  _________________________ Date: _________
  [Name, Title]

  For the Researcher:
  _________________________ Date: _________
  [Name, Institution]

NOTICE: This template was generated by the Tribal Data Sovereignty
Toolkit. It is a starting point only. Tribal legal counsel should
review and modify this agreement before execution.
Daear Consulting, LLC
"""


# CLI

if __name__ == "__main__":
    import argparse
    from toolkit.sovereignty import SovereigntyContext

    parser = argparse.ArgumentParser(
        description="Tribal Data Sovereignty Toolkit governance.py"
    )
    parser.add_argument("--config", default="config/nation.yaml")
    parser.add_argument("--validate",  action="store_true",
                        help="Validate config")
    parser.add_argument("--statement", action="store_true",
                        help="Print data sovereignty statement")
    parser.add_argument("--checklist", action="store_true",
                        help="Print compliance checklist")
    parser.add_argument("--agreement", metavar="PROJECT",
                        help="Generate data sharing agreement template")
    parser.add_argument("--output", metavar="PATH",
                        help="Save output to file instead of printing")
    args = parser.parse_args()

    ctx = SovereigntyContext.from_config(args.config)

    output_text = None

    if args.validate:
        errors = ctx.config.validate()
        if errors:
            print("Validation warnings:")
            for e in errors:
                print(f"  ! {e}")
        else:
            print(f"Config valid for Nation: {ctx.config.name}")

    if args.statement:
        output_text = data_sovereignty_statement(ctx)

    if args.checklist:
        output_text = compliance_checklist(ctx)

    if args.agreement:
        output_text = data_sharing_template(ctx, project_name=args.agreement)

    if output_text:
        if args.output:
            Path(args.output).write_text(output_text, encoding="utf-8")
            print(f"Saved: {args.output}")
        else:
            print(output_text)
